spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tourgether
    username: jake
    password: nada5011
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true  # Hibernate 초기화 후 SQL 스크립트 실행

  # SQL 초기화 설정 추가
  sql:
    init:
      mode: always  # 항상 SQL 스크립트 실행
      data-locations: classpath:data.sql  # 데이터 초기화 스크립트 위치
      continue-on-error: true  # 오류 발생해도 계속 진행

  twilio:
    # Twilio 계정 식별자
    # Twilio API 인증 토큰
    verify-service-sid: ${TWILIO_VERIFY_SERVICE_SID}  # Twilio Verify 서비스 SID

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email

          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: profile_nickname, profile_image, account_email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  data:
    redis:
      port: 6379
      host: localhost

jwt:
  secret: ${JWT_SECRET_KEY:abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuvwxyz0123456789}
  access-token-validity-in-seconds: 3600  # 1H
  refresh-token-validity-in-seconds: 1209600  # 14D

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    #    org.springframework.security: DEBUG
    com.gdc.tripmate: DEBUG
    #    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE